edition = "2021"
unstable_features = true
version = "Two"

blank_lines_lower_bound = 0
blank_lines_upper_bound = 2
brace_style = "PreferSameLine"
enum_discrim_align_threshold = 32
fn_params_layout = "Compressed"
fn_single_line = true
format_code_in_doc_comments = true
imports_granularity = "Crate"
newline_style = "Unix"
normalize_comments = true
normalize_doc_attributes = true
overflow_delimited_expr = true
reorder_impl_items = true
struct_field_align_threshold = 32
struct_lit_single_line = true
use_field_init_shorthand = true
use_try_shorthand = true
wrap_comments = false
