name: Tests & Checks

on:
  pull_request:
    paths-ignore:
      - ".github/**"
      - "**/*.md"
  push:
    branches:
      - master
    paths-ignore:
      - ".github/**"
      - "**/*.md"
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write
  checks: write
  statuses: write

jobs:

  checks:

    name: Checks
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
        toolchain:
          - 1.77.2

    env:
      RUST_BACKTRACE: full

    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          submodules: recursive
          show-progress: false

      - name: Set up Rust toolchain
        uses: Systemcluster/actions@setup-rust-v0
        with:
          channel: ${{ matrix.toolchain }}
          components: clippy
          cache-key-job: true

      - name: Check check
        run: cargo check --workspace --all-features

      - name: Check clippy
        run: cargo clippy --workspace --all-features

      - name: Check build
        run: cargo build --all-features --verbose

      - name: Check output
        run: |
          target/debug/wrappe --version
          target/debug/wrappe --list-runners
          target/debug/wrappe target/debug/wrappe${{ runner.os == 'Windows' && '.exe' || '' }} target/debug/wrappe${{ runner.os == 'Windows' && '.exe' || '' }} packed${{ runner.os == 'Windows' && '.exe' || '' }}
          ./packed${{ runner.os == 'Windows' && '.exe' || '' }} --version

  formatting:

    name: Formatting
    runs-on: ${{ matrix.os }}

    if: github.event_name == 'pull_request'

    strategy:
      matrix:
        os:
          - ubuntu-latest
        toolchain:
          - nightly

    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          submodules: recursive
          show-progress: false

      - name: Set up Rust toolchain
        uses: Systemcluster/actions@setup-rust-v0
        with:
          channel: ${{ matrix.toolchain }}
          targets: x86_64-unknown-linux-musl
          components: rustfmt
          cache-key-job: true

      - name: Check formatting
        uses: mbrobbel/rustfmt-check@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          mode: review
